title:       "sunnysani OS"
# baseurl: "" # e.g. /blog
# url: ""     # e.g. http://example.com
author:           "Naufal Sani"
sitemap:          "true"
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
urlweb:           "https://sunnysani.github.io/os211/"
urlgithub:        "https://github.com/sunnysani/os211/"
urlghpage:        "https://sunnysani.github.io/os211/"
keywords:         "jekyll, testing"
github:           [metadata]

